openapi: 3.0.3
info:
    title: verification-service
    version: 0.0.0
    description: |
        ...

servers:
    -   url: http://localhost:8080/v1/verification-service
        description: "Local K8s Cluster"
    -   url: http://localhost:8080
        description: "Local API Instance"

paths:
    /:
        get:
            summary: Service Metadata
            responses:
                200:
                    $ref: "#/components/responses/metadata"
    /health:
        get:
            summary: Health-Probe Endpoint
            responses:
                200:
                    $ref: "#/components/responses/health"

components:
    requestBodies:
        example:
            description: Optional description in *Markdown*
            content:
                application/json:
                    schema:
                        type: object
                    example:
                        key: value

    responses:
        example:
            description: Optional description in *Markdown*
            content:
                application/json:
                    schema:
                        type: object
                    example:
                        key: value
        health:
            description: A health check response used by internal probes.
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            status:
                                type: string
                                example: ok
        metadata:
            description: An endpoint response used as entry points by microservices.
            content:
                application/json:
                    schema:
                        type: object
                        additionalProperties:
                            type: string
                            example: example-service
                            properties:
                                path:
                                    type: string
                                    example: /
                                service:
                                    type: string
                                    example: example-service
                                version:
                                    type: string
                                    example: 1.0.0
                                    default: development
                            additionalProperties:
                                type: object
                    example:
                        example-service:
                            path: /
                            service: example-service
                            version: 1.0.0

    securitySchemes:
        Basic:
            description: Basic Username + Password Authentication
            type: http
            scheme: basic
        Bearer:
            description: Bearer token using a JWT
            type: http
            scheme: bearer
            bearerFormat: JWT
        Cookie:
            description: Cookie token using a JWT
            type: apiKey
            in: cookie
            name: token
        API:
            type: apiKey
            in: header
            name: X-API-Key
        OpenID:
            type: openIdConnect
            openIdConnectUrl: https://example.com/.well-known/openid-configuration
        OAuth2:
            type: oauth2
            flows:
                authorizationCode:
                    authorizationUrl: https://example.com/oauth/authorize
                    tokenUrl: https://example.com/oauth/token
                    scopes:
                        read: Grants read access
                        write: Grants write access
                        admin: Grants access to admin operations
