kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: development
commonAnnotations:
    environment: development
images:
    - name: service:latest
      newName: localhost:5050/test-service-2
      newTag: 0.0.34
resources:
    - namespace.yaml
    - application.yaml
