apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#    - namespace.yaml
#    - gateway.yaml
#    - repositories.yaml
#    - istio-base.yaml
#    - istiod.yaml
#    - istio-gateway.yaml
    - namespace.yaml
    - gateway.yaml
    - helm-repository.yaml
    - ./base
    - ./d
