# How to manage values files. Ref: https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-inside-the-chart
# How to inject values: https://fluxcd.io/docs/guides/helmreleases/#cloud-storage
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-secrets
    namespace: flux-system
spec:
    # Override Release name to avoid the pattern Namespace-Release
    # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.HelmRelease
    releaseName: external-secrets
    targetNamespace: external-secrets
    interval: 1m
    chart:
        spec:
            chart: external-secrets
            version: "0.9.17"
            sourceRef:
                kind: HelmRepository
                name: external-secrets
                namespace: flux-system
    values:
        installCRDs: true # prevents race-conditions by allowing kustomize to handle the installation of crds

    # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
    install:
        crds: Create
        createNamespace: true
