// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int64              `db:"id" json:"id"`
	Name         *string            `db:"name" json:"name"`
	DisplayName  *string            `db:"display-name" json:"display-name"`
	Email        string             `db:"email" json:"email"`
	Avatar       *string            `db:"avatar" json:"avatar"`
	Marketing    bool               `db:"marketing" json:"marketing"`
	Creation     pgtype.Timestamptz `db:"creation" json:"creation"`
	Modification pgtype.Timestamptz `db:"modification" json:"modification"`
	Deletion     pgtype.Timestamptz `db:"deletion" json:"deletion"`
}
