apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
    name: kube-prometheus-stack
    namespace: prometheus
spec:
    interval: 10m
    chart: kube-prometheus-stack
    sourceRef:
        kind: HelmRepository
        name: prometheus
    version: "58.5.1"