---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: prometheus
    namespace: prometheus
spec:
    releaseName: kube-prometheus-stack
    targetNamespace: prometheus
    interval: 1m
    timeout: 5m
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    test:
        enable: true
    driftDetection:
        mode: disabled
        ignore: []
    chartRef:
        kind: HelmChart
        name: kube-prometheus-stack
        namespace: prometheus
    values:
        grafana:
            enabled: false
        prometheus:
            enabled: true
            prometheusSpec:
                hostNetwork: false
                additionalScrapeConfigs:
                    -   job_name: 'istiod'
                        kubernetes_sd_configs:
                            -   role: endpoints
                                namespaces:
                                    names:
                                        - istio-system
                        relabel_configs:
                            -   source_labels: [ __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name ]
                                action: keep
                                regex: istiod;http-monitoring
                    -   job_name: 'envoy-stats'
                        metrics_path: /stats/prometheus
                        kubernetes_sd_configs:
                            -   role: pod

                        relabel_configs:
                            -   source_labels: [ __meta_kubernetes_pod_container_port_name ]
                                action: keep
                                regex: '.*-envoy-prom'
