// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package verifications

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Verification struct {
	ID           int64              `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	Code         string             `db:"code" json:"code"`
	Verified     bool               `db:"verified" json:"verified"`
	Creation     pgtype.Timestamptz `db:"creation" json:"creation"`
	Modification pgtype.Timestamptz `db:"modification" json:"modification"`
	Deletion     pgtype.Timestamptz `db:"deletion" json:"deletion"`
}
