# How to manage values files. Ref: https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-inside-the-chart
# How to inject values: https://fluxcd.io/docs/guides/helmreleases/#cloud-storage
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kyverno
    namespace: flux-system
spec:
    releaseName: kyverno-policies
    targetNamespace: kyverno
    interval: 1m
    chart:
        spec:
            chart: kyverno
            version: "3.2.2"
            sourceRef:
                kind: HelmRepository
                name: kyverno
                namespace: flux-system
    values:
        admissionController.replicas: 3
        backgroundController.replicas: 2
        cleanupController.replicas: 2
        reportsController.replicas: 2

    # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
    install:
        crds: Create
        createNamespace: true
