apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
    name: default
spec:
    credentials:
        source: Secret
        secretRef:
            namespace: flux-system
            name: aws-crossplane-provider-credentials
            key: profile
