apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
    name: metrics-server
    namespace: metrics-server
spec:
    interval: 10m
    chart: metrics-server
    sourceRef:
        kind: HelmRepository
        name: metrics-server
    version: "3.12.x"