---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: metrics-server
    namespace: metrics-server
spec:
    releaseName: metrics-server
    targetNamespace: metrics-server
    interval: 1m
    timeout: 5m
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    test:
        enable: true
    driftDetection:
        mode: enabled
        ignore: []
    chartRef:
        kind: HelmChart
        name: metrics-server
        namespace: metrics-server
    values:
        args:
            - "--kubelet-insecure-tls"