---
apiVersion: v1
kind: LimitRange
metadata:
    name: limit-range
spec:
    limits:
        -   type: Pod
            max:
                cpu: "1"
                memory: 1Gi
        -   type: Container
            default:
                cpu: "500m"
                memory: "512Mi"
            defaultRequest:
                cpu: "250m"
                memory: "256Mi"
