# How to manage values files. Ref: https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-inside-the-chart
# How to inject values: https://fluxcd.io/docs/guides/helmreleases/#cloud-storage
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: crossplane
    namespace: flux-system
spec:
    releaseName:  crossplane
    targetNamespace: crossplane-system
    interval: 1m
    chart:
        spec:
            chart: crossplane
            version: "1.16.0"
            sourceRef:
                kind: HelmRepository
                name: crossplane
                namespace: flux-system

    # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
    install:
        crds: Create
        createNamespace: true
