apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
    name: istio-base
    namespace: istio-system
spec:
    interval: 10m
    chart: base
    sourceRef:
        kind: HelmRepository
        name: istio
    version: "1.23.x"