---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: istio-ingressgateway
    namespace: istio-system
spec:
    releaseName: istio-ingressgateway
    targetNamespace: istio-system
    interval: 1m
    timeout: 5m
    install:
        disableWait: false
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    test:
        enable: true
    driftDetection:
        mode: disabled
        ignore: []
    chartRef:
        kind: HelmChart
        name: istio-ingressgateway
        namespace: istio-system
    values:
        defaults:
            autoscaling:
                enabled: false