---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: verification-service
spec:
    template:
        spec:
            containers:
                -   name: verification-service
                    env:
                        -   name: PGDATABASE
                            value: verification-service
                        -   name: PGPORT
                            valueFrom:
                                secretKeyRef:
                                    optional: false
                                    name: postgres-cluster-superuser
                                    key: port
                        -   name: PGHOST
                            valueFrom:
                                secretKeyRef:
                                    optional: false
                                    name: postgres-cluster-superuser
                                    key: host
                        -   name: PGUSER
                            valueFrom:
                                secretKeyRef:
                                    optional: false
                                    name: postgres-cluster-superuser
                                    key: username
                        -   name: PGPASSWORD
                            valueFrom:
                                secretKeyRef:
                                    optional: false
                                    name: postgres-cluster-superuser
                                    key: password
