# permissions for end users to view helms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: installer
    app.kubernetes.io/managed-by: kustomize
  name: helm-viewer-role
rules:
- apiGroups:
  - installer.operators.ethr.gg
  resources:
  - helms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - installer.operators.ethr.gg
  resources:
  - helms/status
  verbs:
  - get
