apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
    name: istio-egressgateway
    namespace: istio-system
spec:
    interval: 10m
    chart: gateway
    sourceRef:
        kind: HelmRepository
        name: istio
    version: "1.23.x"