apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: cluster-secret-store
spec:
    provider:
        aws:
            service: SecretsManager
            region: us-east-2
            auth:
                secretRef:
                    accessKeyIDSecretRef:
                        key: aws-access-key-id
                        name: aws-secrets-manager-bootstrap
                        namespace: cloud-provider-system
                    secretAccessKeySecretRef:
                        key: aws-secret-access-key
                        name: aws-secrets-manager-bootstrap
                        namespace: cloud-provider-system
            secretsManager:
                forceDeleteWithoutRecovery: true
