---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: cert-manager
    namespace: flux-system
spec:
    interval: 1m
    path: ./applications/cert-manager
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
