---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: crossplane
    namespace: flux-system
spec:
    interval: 1m
    path: ./applications/crossplane
    prune: true
    dependsOn:
        -   name: external-secrets
            namespace: flux-system
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
